function E = Energy_stance(s,phi,theta,ds,dphi,dtheta,g,k,L_sp0,L_m1,m1,I1)
%ENERGY
%    E = ENERGY(S,PHI,THETA,DS,DPHI,DTHETA,X2,Y2,G,K,L_SP0,L_M1,M1,I1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 23:58:14

t2 = dphi-dtheta;
t3 = L_sp0-s;
E = I1.*t2.^2.*(1.0./2.0)+k.*t3.^2.*(1.0./2.0)+m1.*(ds.^2+dphi.^2.*s.^2).*(1.0./2.0)+g.*m1.*s.*cos(phi);
