function f_cg = F_CoriGrav_st_L(s1,phi1,theta,s2,phi2,ds1,dphi1,dtheta,ds2,dphi2,g,k1,k2,L_sp0,L_mB,mB,IB,m1)
%F_CORIGRAV
%    F_CG = F_CORIGRAV(S1,PHI1,THETA,S2,PHI2,DS1,DPHI1,DTHETA,DS2,DPHI2,X2,Y2,G,K1,K2,L_SP0,L_MB,MB,IB,M1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 12:59:24

t2 = dphi2.^2;
t3 = phi1-theta;
t4 = phi1+phi2-theta;
t5 = cos(t3);
t6 = sin(t3);
t7 = dphi1.*ds1.*2.0;
t8 = dphi2.*ds1.*2.0;
t9 = sin(t4);
t10 = g.*t9;
t11 = t7+t8+t10-ds1.*dtheta.*2.0-dphi2.*ds2.*t5.*2.0-s2.*t2.*t6;
t12 = cos(phi2);
t13 = dphi1.^2;
t14 = dtheta.^2;
t15 = sin(phi2);
f_cg = [L_sp0.*k1-k1.*s1+g.*m1.*cos(t4)+m1.*s1.*t2+m1.*s1.*t13+m1.*s1.*t14+dphi1.*dphi2.*m1.*s1.*2.0-dphi1.*dtheta.*m1.*s1.*2.0-dphi2.*dtheta.*m1.*s1.*2.0+dphi2.*ds2.*m1.*t6.*2.0-m1.*s2.*t2.*t5;-m1.*s1.*t11;m1.*s1.*t11;L_sp0.*k2-k2.*s2-g.*m1.*t12-g.*mB.*t12+m1.*s2.*t2+mB.*s2.*t2-dphi1.*ds1.*m1.*t6.*2.0-dphi2.*ds1.*m1.*t6.*2.0+ds1.*dtheta.*m1.*t6.*2.0-m1.*s1.*t2.*t5-m1.*s1.*t5.*t13-m1.*s1.*t5.*t14-dphi1.*dphi2.*m1.*s1.*t5.*2.0+dphi1.*dtheta.*m1.*s1.*t5.*2.0+dphi2.*dtheta.*m1.*s1.*t5.*2.0;dphi1.*ds1.*m1.*s1.*-2.0-dphi2.*ds1.*m1.*s1.*2.0-dphi2.*ds2.*m1.*s2.*2.0+ds1.*dtheta.*m1.*s1.*2.0-dphi2.*ds2.*mB.*s2.*2.0-g.*m1.*s1.*t9+g.*m1.*s2.*t15+g.*mB.*s2.*t15+dphi1.*ds1.*m1.*s2.*t5.*2.0+dphi2.*ds1.*m1.*s2.*t5.*2.0+dphi2.*ds2.*m1.*s1.*t5.*2.0-ds1.*dtheta.*m1.*s2.*t5.*2.0-m1.*s1.*s2.*t6.*t13-m1.*s1.*s2.*t6.*t14-dphi1.*dphi2.*m1.*s1.*s2.*t6.*2.0+dphi1.*dtheta.*m1.*s1.*s2.*t6.*2.0+dphi2.*dtheta.*m1.*s1.*s2.*t6.*2.0];
