function invM = InvMassMatrix_st_L(s1,phi1,theta,s2,phi2,g,k1,k2,L_sp0,L_mB,mB,IB,m1)
%INVMASSMATRIX
%    INVM = INVMASSMATRIX(S1,PHI1,THETA,S2,PHI2,X2,Y2,G,K1,K2,L_SP0,L_MB,MB,IB,M1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 12:59:23

t2 = 1.0./mB;
t3 = phi1-theta;
t4 = 1.0./s2;
t5 = sin(t3);
t6 = t2.*t4.*t5;
t7 = 1.0./m1;
t8 = 1.0./IB;
t9 = cos(t3);
t10 = 1.0./s1;
t11 = IB.*t9;
t12 = mB.*s1.*s2;
t13 = t11+t12;
t14 = t2.*t4.*t8.*t10.*t13;
t15 = 1.0./s2.^2;
t16 = t2.*t9;
t17 = t2.*t4.*t9.*t10;
t18 = t2.*t15;
invM = reshape([t2.*t7.*(m1+mB),0.0,t6,t16,t6,0.0,1.0./s1.^2.*t2.*t7.*t8.*(IB.*m1+IB.*mB+m1.*mB.*s1.^2),t14,-t2.*t5.*t10,t17,t6,t14,t2.*t8.*t15.*(IB+mB.*s2.^2),0.0,t18,t16,-t2.*t5.*t10,0.0,t2,0.0,t6,t17,t18,0.0,t18],[5,5]);
