function BodyL = BodyL(xB,yB,theta,s1,phi1,s2,phi2,g,k1,k2,L_sp0,L_mB,mB,IB,m1,m2)
%BODYL
%    BODYL = BODYL(XB,YB,THETA,S1,PHI1,S2,PHI2,G,K1,K2,L_SP0,L_MB,MB,IB,M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:12:20

BodyL = [xB-L_mB.*cos(theta).*(1.0./2.0);yB-L_mB.*sin(theta).*(1.0./2.0)];
