function invM = InvMassMatrix(xB,yB,theta,s1,phi1,s2,phi2,g,k1,k2,L_sp0,L_mB,mB,IB,m1,m2)
%INVMASSMATRIX
%    INVM = INVMASSMATRIX(XB,YB,THETA,S1,PHI1,S2,PHI2,G,K1,K2,L_SP0,L_MB,MB,IB,M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:12:20

t2 = 1.0./mB;
t3 = phi1+theta;
t4 = phi2+theta;
t5 = cos(t3);
t6 = 1.0./s1;
t7 = sin(t3);
t8 = cos(t4);
t9 = 1.0./s2;
t10 = sin(t4);
t11 = 1.0./IB;
t12 = t2.*t5;
t13 = phi1-phi2;
t14 = 1.0./m1;
t15 = sin(t13);
t16 = cos(t13);
t17 = t2.*t8;
t18 = t2.*t16;
t19 = t2.*t9.*t15;
t20 = IB.*t16;
t21 = mB.*s1.*s2;
t22 = t20+t21;
t23 = t2.*t6.*t9.*t11.*t22;
t24 = 1.0./m2;
t25 = IB.*mB;
invM = reshape([t2,0.0,0.0,-t2.*t7,-t2.*t5.*t6,-t2.*t10,-t2.*t8.*t9,0.0,t2,0.0,t12,-t2.*t6.*t7,t17,-t2.*t9.*t10,0.0,0.0,t11,0.0,-t11,0.0,-t11,-t2.*t7,t12,0.0,t2.*t14.*(m1+mB),0.0,t18,t19,-t2.*t5.*t6,-t2.*t6.*t7,-t11,0.0,1.0./s1.^2.*t2.*t11.*t14.*(t25+IB.*m1+m1.*mB.*s1.^2),-t2.*t6.*t15,t23,-t2.*t10,t17,0.0,t18,-t2.*t6.*t15,t2.*t24.*(m2+mB),0.0,-t2.*t8.*t9,-t2.*t9.*t10,-t11,t19,t23,0.0,1.0./s2.^2.*t2.*t11.*t24.*(t25+IB.*m2+m2.*mB.*s2.^2)],[7,7]);
