function M = MassMatrix(xB,yB,theta,s1,phi1,s2,phi2,g,k1,k2,L_sp0,L_mB,mB,IB,m1,m2)
%MASSMATRIX
%    M = MASSMATRIX(XB,YB,THETA,S1,PHI1,S2,PHI2,G,K1,K2,L_SP0,L_MB,MB,IB,M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:12:19

t2 = phi1+theta;
t3 = cos(t2);
t4 = m1.*s1.*t3;
t5 = phi2+theta;
t6 = cos(t5);
t7 = m2.*s2.*t6;
t8 = m1+m2+mB;
t9 = sin(t2);
t10 = sin(t5);
t11 = m1.*s1.*t9;
t12 = m2.*s2.*t10;
t13 = t4+t7;
t14 = t11+t12;
t15 = s1.^2;
t16 = m1.*t15;
t17 = s2.^2;
t18 = m2.*t17;
t19 = m1.*t9;
t20 = m2.*t10;
M = reshape([t8,0.0,t13,t19,t4,t20,t7,0.0,t8,t14,-m1.*t3,t11,-m2.*t6,t12,t13,t14,IB+t16+t18,0.0,t16,0.0,t18,t19,-m1.*t3,0.0,m1,0.0,0.0,0.0,t4,t11,t16,0.0,t16,0.0,0.0,t20,-m2.*t6,0.0,0.0,0.0,m2,0.0,t7,t12,t18,0.0,0.0,0.0,t18],[7,7]);
