function BodyL = BodyL(s1,phi1,theta,s2,phi2,x1,y1,g,k1,k2,L_sp0,L_mB,mB,IB,m2)
%BODYL
%    BODYL = BODYL(S1,PHI1,THETA,S2,PHI2,X1,Y1,G,K1,K2,L_SP0,L_MB,MB,IB,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:29:06

t2 = phi1-theta;
BodyL = [x1-L_mB.*cos(t2)-s1.*sin(phi1);-L_mB.*sin(t2)+s1.*cos(phi1)];
