function CoGs = CoGPositions(s1,phi1,theta,s2,phi2,x1,y1,g,k1,k2,L_sp0,L_mB,mB,IB,m2)
%COGPOSITIONS
%    COGS = COGPOSITIONS(S1,PHI1,THETA,S2,PHI2,X1,Y1,G,K1,K2,L_SP0,L_MB,MB,IB,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:29:06

t2 = sin(phi1);
t3 = phi1+phi2-theta;
t4 = cos(phi1);
t5 = s1.*t4;
CoGs = reshape([x1,y1,0.0,x1-s1.*t2,t5,phi1-theta,x1-s1.*t2+s2.*sin(t3),t5-s2.*cos(t3),0.0],[3,3]);
