function JBodyL = ContactJacobianL(s1,phi1,theta,s2,phi2,x1,y1,g,k1,k2,L_sp0,L_mB,mB,IB,m2)
%CONTACTJACOBIANL
%    JBODYL = CONTACTJACOBIANL(S1,PHI1,THETA,S2,PHI2,X1,Y1,G,K1,K2,L_SP0,L_MB,MB,IB,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:29:06

t2 = phi1-theta;
t3 = sin(t2);
t4 = L_mB.*t3;
t5 = cos(phi1);
t6 = sin(phi1);
t7 = cos(t2);
JBodyL = reshape([-t6,t5,t4-s1.*t5,-L_mB.*t7-s1.*t6,-t4,L_mB.*t7,0.0,0.0,0.0,0.0],[2,5]);
