function ContactPointR = ContactPointR(x,y,thetaL,thetaR,g,lCG,lL,mL,jL)
%CONTACTPOINTR
%    CONTACTPOINTR = CONTACTPOINTR(X,Y,THETAL,THETAR,G,LCG,LL,ML,JL)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 14:10:15

ContactPointR = [x+lL.*sin(thetaR);y-lL.*cos(thetaR)];
