function E = Energy(s1,phi1,theta,s2,phi2,ds1,dphi1,dtheta,ds2,dphi2,x1,y1,g,k1,k2,L_sp0,L_mB,mB,IB,m2)
%ENERGY
%    E = ENERGY(S1,PHI1,THETA,S2,PHI2,DS1,DPHI1,DTHETA,DS2,DPHI2,X1,Y1,G,K1,K2,L_SP0,L_MB,MB,IB,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:29:06

t2 = ds1.^2;
t3 = L_sp0-s1;
t4 = L_sp0-s2;
t5 = dphi1.^2;
t6 = s2.^2;
t7 = dtheta.^2;
t8 = s1.^2;
t9 = cos(phi1);
t10 = phi2-theta;
t11 = sin(t10);
t12 = cos(t10);
E = IB.*t5.*(1.0./2.0)+IB.*t7.*(1.0./2.0)+m2.*t2.*(1.0./2.0)+mB.*t2.*(1.0./2.0)+ds2.^2.*m2.*(1.0./2.0)+k1.*t3.^2.*(1.0./2.0)+k2.*t4.^2.*(1.0./2.0)+dphi2.^2.*m2.*t6.*(1.0./2.0)+g.*m2.*(s1.*t9-s2.*cos(phi1+phi2-theta))-IB.*dphi1.*dtheta+m2.*t5.*t6.*(1.0./2.0)+m2.*t5.*t8.*(1.0./2.0)+m2.*t6.*t7.*(1.0./2.0)+mB.*t5.*t8.*(1.0./2.0)+dphi1.*dphi2.*m2.*t6-dphi1.*dtheta.*m2.*t6-dphi2.*dtheta.*m2.*t6-ds1.*ds2.*m2.*t12+g.*mB.*s1.*t9+dphi1.*ds1.*m2.*s2.*t11-dphi1.*ds2.*m2.*s1.*t11+dphi2.*ds1.*m2.*s2.*t11-ds1.*dtheta.*m2.*s2.*t11-m2.*s1.*s2.*t5.*t12-dphi1.*dphi2.*m2.*s1.*s2.*t12+dphi1.*dtheta.*m2.*s1.*s2.*t12;
