function f_cg = F_CoriGrav(s1,phi1,theta,s2,phi2,ds1,dphi1,dtheta,ds2,dphi2,x1,y1,g,k1,k2,L_sp0,L_mB,mB,IB,m2)
%F_CORIGRAV
%    F_CG = F_CORIGRAV(S1,PHI1,THETA,S2,PHI2,DS1,DPHI1,DTHETA,DS2,DPHI2,X1,Y1,G,K1,K2,L_SP0,L_MB,MB,IB,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:29:05

t2 = dphi1.^2;
t3 = cos(phi1);
t4 = phi2-theta;
t5 = cos(t4);
t6 = sin(t4);
t7 = sin(phi1);
t8 = dphi2.^2;
t9 = dtheta.^2;
t10 = phi1+phi2-theta;
t11 = sin(t10);
t12 = dphi1.*ds2.*2.0;
t13 = dphi2.*ds2.*2.0;
t14 = g.*t11;
t15 = t12+t13+t14-ds2.*dtheta.*2.0-dphi1.*ds1.*t5.*2.0-s1.*t2.*t6;
t16 = m2.*s2.*t15;
f_cg = [L_sp0.*k1-k1.*s1-g.*m2.*t3-g.*mB.*t3+m2.*s1.*t2+mB.*s1.*t2-dphi1.*ds2.*m2.*t6.*2.0-dphi2.*ds2.*m2.*t6.*2.0+ds2.*dtheta.*m2.*t6.*2.0-m2.*s2.*t2.*t5-m2.*s2.*t5.*t8-m2.*s2.*t5.*t9-dphi1.*dphi2.*m2.*s2.*t5.*2.0+dphi1.*dtheta.*m2.*s2.*t5.*2.0+dphi2.*dtheta.*m2.*s2.*t5.*2.0;dphi1.*ds1.*m2.*s1.*-2.0-dphi1.*ds2.*m2.*s2.*2.0-dphi2.*ds2.*m2.*s2.*2.0+ds2.*dtheta.*m2.*s2.*2.0-dphi1.*ds1.*mB.*s1.*2.0+g.*m2.*s1.*t7-g.*m2.*s2.*t11+g.*mB.*s1.*t7+dphi1.*ds1.*m2.*s2.*t5.*2.0+dphi1.*ds2.*m2.*s1.*t5.*2.0+dphi2.*ds2.*m2.*s1.*t5.*2.0-ds2.*dtheta.*m2.*s1.*t5.*2.0-m2.*s1.*s2.*t6.*t8-m2.*s1.*s2.*t6.*t9-dphi1.*dphi2.*m2.*s1.*s2.*t6.*2.0+dphi1.*dtheta.*m2.*s1.*s2.*t6.*2.0+dphi2.*dtheta.*m2.*s1.*s2.*t6.*2.0;t16;L_sp0.*k2-k2.*s2+g.*m2.*cos(t10)+m2.*s2.*t2+m2.*s2.*t8+m2.*s2.*t9+dphi1.*dphi2.*m2.*s2.*2.0-dphi1.*dtheta.*m2.*s2.*2.0-dphi2.*dtheta.*m2.*s2.*2.0+dphi1.*ds1.*m2.*t6.*2.0-m2.*s1.*t2.*t5;-t16];
