function M = MassMatrix(s1,phi1,theta,s2,phi2,x1,y1,g,k1,k2,L_sp0,L_mB,mB,IB,m2)
%MASSMATRIX
%    M = MASSMATRIX(S1,PHI1,THETA,S2,PHI2,X1,Y1,G,K1,K2,L_SP0,L_MB,MB,IB,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:29:05

t2 = phi2-theta;
t3 = sin(t2);
t4 = m2.*s2.*t3;
t5 = s1.^2;
t6 = cos(t2);
t7 = s2.^2;
t8 = m2.*t7;
t9 = m2.*s1.*s2.*t6;
t10 = -IB-t8+t9;
t11 = s2-s1.*t6;
t12 = m2.*s2.*t11;
M = reshape([m2+mB,t4,-t4,-m2.*t6,t4,t4,IB+t8+m2.*t5+mB.*t5-m2.*s1.*s2.*t6.*2.0,t10,-m2.*s1.*t3,t12,-t4,t10,IB+t8,0.0,-t8,-m2.*t6,-m2.*s1.*t3,0.0,m2,0.0,t4,t12,-t8,0.0,t8],[5,5]);
