function BodyR = BodyR(s1,phi1,theta,s2,phi2,x2,y2,g,k1,k2,L_sp0,L_mB,mB,IB,m1)
%BODYR
%    BODYR = BODYR(S1,PHI1,THETA,S2,PHI2,X2,Y2,G,K1,K2,L_SP0,L_MB,MB,IB,M1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 12:59:24

t2 = phi2-theta;
BodyR = [x2+L_mB.*cos(t2)-s2.*sin(phi2);L_mB.*sin(t2)+s2.*cos(phi2)];
