function CoGs = CoGPositions(s1,phi1,theta,s2,phi2,x2,y2,g,k1,k2,L_sp0,L_mB,mB,IB,m1)
%COGPOSITIONS
%    COGS = COGPOSITIONS(S1,PHI1,THETA,S2,PHI2,X2,Y2,G,K1,K2,L_SP0,L_MB,MB,IB,M1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 12:59:25

t2 = sin(phi2);
t3 = phi1+phi2-theta;
t4 = cos(phi2);
t5 = s2.*t4;
CoGs = reshape([x2,y2,0.0,x2-s2.*t2,t5,phi1-theta,x2-s2.*t2+s1.*sin(t3),t5-s1.*cos(t3),0.0],[3,3]);
