function JBodyR = ContactJacobianR(s1,phi1,theta,s2,phi2,x2,y2,g,k1,k2,L_sp0,L_mB,mB,IB,m1)
%CONTACTJACOBIANR
%    JBODYR = CONTACTJACOBIANR(S1,PHI1,THETA,S2,PHI2,X2,Y2,G,K1,K2,L_SP0,L_MB,MB,IB,M1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 12:59:25

t2 = phi2-theta;
t3 = sin(t2);
t4 = L_mB.*t3;
t5 = cos(phi2);
t6 = cos(t2);
t7 = sin(phi2);
JBodyR = reshape([0.0,0.0,0.0,0.0,t4,-L_mB.*t6,-t7,t5,-t4-s2.*t5,L_mB.*t6-s2.*t7],[2,5]);
