function links = LinkPositions(s1,phi1,theta,s2,phi2,x2,y2,g,k1,k2,L_sp0,L_mB,mB,IB,m1)
%LINKPOSITIONS
%    LINKS = LINKPOSITIONS(S1,PHI1,THETA,S2,PHI2,X2,Y2,G,K1,K2,L_SP0,L_MB,MB,IB,M1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 12:59:25

t2 = phi2-theta;
t3 = cos(t2);
t4 = sin(phi2);
t5 = cos(phi2);
t6 = s2.*t5;
t7 = sin(t2);
t8 = phi1+phi2-theta;
links = reshape([x2-L_mB.*t3-s2.*t4,t6-L_mB.*t7,x2+L_mB.*t3-s2.*t4,t6+L_mB.*t7,x2-s2.*t4,t6,x2-s2.*t4+s1.*sin(t8),t6-s1.*cos(t8),x2,y2],[2,5]);
