function links = LinkPositions(xB,yB,theta,s1,phi1,s2,phi2,L_mB)
%LINKPOSITIONS
%    LINKS = LINKPOSITIONS(XB,YB,THETA,S1,PHI1,S2,PHI2,G,K1,K2,L_SP0,L_MB,MB,IB,M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jan-2017 01:12:21

t2 = cos(theta);
t3 = sin(theta);
t4 = phi1+theta;
t5 = phi2+theta;
links = reshape([xB-L_mB.*t2.*(1.0./2.0),yB-L_mB.*t3.*(1.0./2.0),xB+L_mB.*t2.*(1.0./2.0),yB+L_mB.*t3.*(1.0./2.0),xB,yB,xB+s1.*sin(t4),yB-s1.*cos(t4),xB+s2.*sin(t5),yB-s2.*cos(t5)],[2,5]);
